### ISSUE TITLE
createStore can take an enhancer as an optional argument

### ISSUE THREAD

**Issue by amardeep** [rangle/typings-redux#2]
https://github.com/reactjs/redux/blob/master/docs/api/createStore.md

**Comment by gitawego** [comment]
hope this will be updated soon

**Comment by bennett000** [comment]
This has been fixed in commit: a840c76f958eb791da747ef9a4eb2f98d6c964c6

@amardeep and @gitawego are you happy with a plain `Function` type or do you see room for a better typing?  

Also: 

- do either of you have opinions on adding generics to `Action`s 
- do either of you have opinions about scrapping IAction and using unions instead of an empty interface?

Lastly, thanks for your interest!

**Comment by bennett000** [comment]
@amardeep and @gitawego Redux is implementing [official typings](https://github.com/reactjs/redux/pull/1413 "Redux Official Typings PR")

This repository (typings-redux) will be deprecated.
